---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Roles
  - ./roles/ml-pipeline-ui.yaml

  # Rolebindings
  - ./rolebindings/ml-pipeline-ui.yaml

  # ServiceAccounts
  - ./serviceaccounts/ml-pipeline-ui.yaml
  - ./serviceaccounts/ml-pipeline-visualizationserver.yaml

  # Configmaps
  - ./configmaps/ml-pipeline-ui-configmap.yaml

  # Deployments
  - ./deployments/ml-pipeline-ui.yaml
  - ./deployments/ml-pipeline-visualizationserver.yaml

  # Services
  - ./services/ml-pipeline-ui.yaml
  - ./services/ml-pipeline-visualizationserver.yaml

  # Routes
  - ./routes/ml-pipeline-ui.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: frontend
    newName: quay.io/internaldatahub/frontend
    newTag: 1.1.0
  - name: visualization-server
    newName: gcr.io/ml-pipeline/visualization-server
    newTag: 1.7.0
