apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: pipelines
  namespace: odh-applications
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: jupyterhub/jupyterhub
      name: jupyterhub
    - kustomizeConfig:
        overlays:
          - additional
        repoRef:
          name: manifests
          path: jupyterhub/notebook-images
      name: notebook-images
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-dashboard
      name: odh-dashboard
    - kustomizeConfig:
        overlays:
          - metadata-store-mysql
          - ml-pipeline-ui
        repoRef:
          name: manifests
          path: ml-pipelines
      name: ml-pipelines
  repos:
    - name: manifests
      uri: "https://github.com/opendatahub-io/odh-manifests/tarball/master"
